api_platform:
    mapping:
        paths:
            - '%kernel.project_dir%/config/api_platform/resources'

    formats:
        jsonld: ['application/ld+json']
        multipart: ['multipart/form-data']

    swagger:
        versions: [3]
        api_keys:
            apiKey:
                name: AuthorizationStart
                type: header

    enable_re_doc: true
    enable_swagger_ui: true
    show_webby: false
    title: Open Rally Edge
    version: 1.0
