parameters:

imports:
    - { resource: 'api_platform/filters/search-filter.yaml' }
    - { resource: 'api_platform/filters/order-filter.yaml' }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $clientId: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            $clientSecret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\Action\:
        resource: '../src/Controller/Action/'
        tags: ['controller.service_arguments']

    App\Controller\Listener\ExceptionResponseTransformerListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 100 }

    App\Controller\Listener\JWTCreatedListener:
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_jwt_created, method: onJWTCreated }

    # AWS for user avatar
    app.images.s3:
        class: Aws\S3\S3Client
        arguments:
            - version: '%env(resolve:VERSION)%'
              region: '%env(resolve:REGION)%'

              credentials:
                  key: '%env(resolve:KEY)%'
                  secret: '%env(resolve:SECRET)%'
